set TrainingSourceDir="D:\\EHUBox\\AnnotationsEditor\\Annotations\\Json"
set EvaluationSourceDir="D:\\EHUBox\\AnnotationsEditor\\Annotations\\Json"
set OutputDir="D:\\EHUBox\\AnnotationsEditor\\Annotations\\Models"
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\Annotations" --paths.train "%TrainingSourceDir%\\Annotations.spacy" --paths.dev "%EvaluationSourceDir%\\Annotations.spacy" --gpu-id 0 > Annotations.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\AcademicDegree" --paths.train "%TrainingSourceDir%\\AcademicDegree.spacy" --paths.dev "%EvaluationSourceDir%\\AcademicDegree.spacy" --gpu-id 0 > AcademicDegree.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\AcademicGrant" --paths.train "%TrainingSourceDir%\\AcademicGrant.spacy" --paths.dev "%EvaluationSourceDir%\\AcademicGrant.spacy" --gpu-id 0 > AcademicGrant.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\AcademicPhd" --paths.train "%TrainingSourceDir%\\AcademicPhd.spacy" --paths.dev "%EvaluationSourceDir%\\AcademicPhd.spacy" --gpu-id 0 > AcademicPhd.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\Book" --paths.train "%TrainingSourceDir%\\Book.spacy" --paths.dev "%EvaluationSourceDir%\\Book.spacy" --gpu-id 0 > Book.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\BookChapter" --paths.train "%TrainingSourceDir%\\BookChapter.spacy" --paths.dev "%EvaluationSourceDir%\\BookChapter.spacy" --gpu-id 0 > BookChapter.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\EducInnovProject" --paths.train "%TrainingSourceDir%\\EducInnovProject.spacy" --paths.dev "%EvaluationSourceDir%\\EducInnovProject.spacy" --gpu-id 0 > EducInnovProject.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\EducQualityEvaluation" --paths.train "%TrainingSourceDir%\\EducQualityEvaluation.spacy" --paths.dev "%EvaluationSourceDir%\\EducQualityEvaluation.spacy" --gpu-id 0 > EducQualityEvaluation.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\EducTraining" --paths.train "%TrainingSourceDir%\\EducTraining.spacy" --paths.dev "%EvaluationSourceDir%\\EducTraining.spacy" --gpu-id 0 > EducTraining.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\IndexedJournalArticle" --paths.train "%TrainingSourceDir%\\IndexedJournalArticle.spacy" --paths.dev "%EvaluationSourceDir%\\IndexedJournalArticle.spacy" --gpu-id 0 > IndexedJournalArticle.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\LanguageCertificate" --paths.train "%TrainingSourceDir%\\LanguageCertificate.spacy" --paths.dev "%EvaluationSourceDir%\\LanguageCertificate.spacy" --gpu-id 0 > LanguageCertificate.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\Phd" --paths.train "%TrainingSourceDir%\\Phd.spacy" --paths.dev "%EvaluationSourceDir%\\Phd.spacy" --gpu-id 0 > Phd.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\ProceedingsArticle" --paths.train "%TrainingSourceDir%\\ProceedingsArticle.spacy" --paths.dev "%EvaluationSourceDir%\\ProceedingsArticle.spacy" --gpu-id 0 > ProceedingsArticle.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\ProfessionalJob" --paths.train "%TrainingSourceDir%\\ProfessionalJob.spacy" --paths.dev "%EvaluationSourceDir%\\ProfessionalJob.spacy" --gpu-id 0 > ProfessionalJob.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\ResearchProject" --paths.train "%TrainingSourceDir%\\ResearchProject.spacy" --paths.dev "%EvaluationSourceDir%\\ResearchProject.spacy" --gpu-id 0 > ResearchProject.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\Stay" --paths.train "%TrainingSourceDir%\\Stay.spacy" --paths.dev "%EvaluationSourceDir%\\Stay.spacy" --gpu-id 0 > Stay.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\StudentProject" --paths.train "%TrainingSourceDir%\\StudentProject.spacy" --paths.dev "%EvaluationSourceDir%\\StudentProject.spacy" --gpu-id 0 > StudentProject.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\Subject" --paths.train "%TrainingSourceDir%\\Subject.spacy" --paths.dev "%EvaluationSourceDir%\\Subject.spacy" --gpu-id 0 > Subject.log
python -m spacy train config.cfg --code functions.py --output "%OutputDir%\\PersonalData" --paths.train "%TrainingSourceDir%\\PersonalData.spacy" --paths.dev "%EvaluationSourceDir%\\PersonalData.spacy" --gpu-id 0 > PersonalData.log